# Generated by Django 2.1.1 on 2022-02-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='active_deposit',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='last_deposit',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='last_withdrawal',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='pending_withdrawal',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='total_balance',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='total_deposit',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='total_withdrawal',
        ),
    ]
